ARG OS_NAME
ARG OS_VERSION

FROM ${OS_NAME}:${OS_VERSION}
ARG OS_NAME
ARG OS_VERSION
ARG FRR_VERSION

WORKDIR /tmp

RUN apt-get update --quiet \
 && apt-get install \
    --yes \
    --no-install-recommends \
    --quiet \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
 # install frr from frrouting debian package repo
 && curl -fLsS https://deb.frrouting.org/frr/keys.asc | apt-key add - \
 && add-apt-repository "deb [arch=amd64] https://deb.frrouting.org/frr $(lsb_release -s -c) ${FRR_VERSION}" \
 && apt update \
 && apt install --yes --no-install-recommends frr frr-pythontools nftables netbase

 ENV OS_NAME=${OS_NAME}
 ENV OS_VERSION=${OS_VERSION}
 ENV FRR_VERSION=${FRR_VERSION}
 COPY validate_os.sh /
