ARG OS_NAME=debian
ARG OS_VERSION=12

FROM ${OS_NAME}:${OS_VERSION}
ARG OS_NAME
ARG OS_VERSION
ARG FRR_VERSION
ARG FRR_APT_CHANNEL

WORKDIR /tmp

RUN apt-get update --quiet \
 && apt-get install \
    --yes \
    --no-install-recommends \
    --quiet \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
 # install frr from frrouting debian package repo
 && curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null \
 && echo "deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr ${FRR_APT_CHANNEL} ${FRR_VERSION}" > /etc/apt/sources.list.d/frr.list \
 && apt update \
 && apt install --yes --no-install-recommends frr frr-pythontools nftables netbase

 ENV OS_NAME=${OS_NAME}
 ENV OS_VERSION=${OS_VERSION}
 ENV FRR_VERSION=${FRR_VERSION}
 COPY validate_os.sh /
