ARG OS_NAME
ARG OS_VERSION
ARG FRR_VERSION
FROM metalstack/frr:${FRR_VERSION}-${OS_NAME}-${OS_VERSION} AS frr-artifacts

FROM ${OS_NAME}:${OS_VERSION}
ARG OS_NAME
ARG OS_VERSION
ARG FRR_VERSION

WORKDIR /tmp
COPY --from=frr-artifacts /artifacts .

RUN apt-get update --quiet \
 && apt-get install \
    --yes \
    --no-install-recommends \
    --quiet \
    ./frr_*.deb \
    ./frr-pythontools_*.deb \
    ./libyang*.deb

COPY ./pkg/netconf/testdata /testdata
COPY validate_os.sh /
RUN "/validate_os.sh"
