name: master

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.x'
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused
    - name: Build project
      run: make
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build docker image
      run: |
        make docker-build
        make docker-push
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}