name: master

on:
  push:
    branches:
    - master

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Set up Go 1.14
      uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.14.x'
    - name: Build project
      run: make
