name: pr

on:
  pull_request:
    branches:
      - master
    types:
      - assigned
      - edited

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Set up Go 1.15
      uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.15.x'
    - name: Build project
      run: make
    - name: Build and push docker image
      run: |
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-build
        make docker-push
