name: pr

on:
  pull_request:
    branches:
      - master

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Set up Go 1.16
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16.x'
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: run
    - name: Build project
      run: make
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build and push docker image
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make docker-build
        make docker-push
