name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused
    - name: Build project
      run: make

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: metal-networker.tgz

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build and push docker image
      run: |
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        make docker-build
        make docker-push
